---
version: '3'

volumes:
  criptup-source:
    external: true

networks:
  default:  # This network will be used from other projects in order to being able to communicate with the core
    name: criptup-net
    ipam:
      driver: default

services:
  nodejs:
    container_name: criptup.nodejs
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    depends_on:
      - redis
    command: sleep infinity
    volumes:
      - criptup-source:/var/ts:delegated
    ports:
      - 6060:6060 # port for express app
      - 3000:3000 # port for queue monitor

  ganache:
    image: trufflesuite/ganache:v7.2.0
    container_name: criptup.ganache
    restart: unless-stopped
    volumes:
      - criptup-source:/var/ts:delegated
    ports:
      - 8545:8545
    command: --db=/var/ts/ganache-db -d -b 5

  redis:
    image: redis
    container_name: criptup.redis
    restart: unless-stopped
    ports:
      - 6379:6379
    sysctls:
        - net.core.somaxconn=512